# Generated by Django 4.2.1 on 2023-05-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueticket',
            name='body',
            field=models.TextField(max_length=512),
        ),
    ]
