# Generated by Django 4.2.1 on 2023-05-28 16:31

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0001_initial'),
        ('SIGT', '0002_alter_issueticket_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48)),
                ('sub_title', models.CharField(max_length=96)),
                ('body', ckeditor.fields.RichTextField(max_length=512)),
                ('tipe', models.CharField(choices=[('IN', 'Incident'), ('RQ', 'Request')], max_length=2)),
                ('level', models.CharField(choices=[('Low', 'Bajo'), ('Mid', 'Medio'), ('Hi', 'Alta'), ('VHI', 'Critico')], default='Mid', max_length=3)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Perfiles.users')),
            ],
        ),
        migrations.DeleteModel(
            name='IssueTicket',
        ),
    ]
