# Generated by Django 4.2.1 on 2023-05-28 21:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIGT', '0003_ticket_delete_issueticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
