# Generated by Django 4.2.1 on 2023-05-29 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0002_perfil'),
        ('SIGT', '0004_alter_ticket_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Perfiles.perfil'),
        ),
    ]
