# Generated by Django 4.2.1 on 2023-05-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('last_name', models.CharField(max_length=48)),
                ('email', models.EmailField(max_length=254)),
                ('cel_phone', models.CharField(max_length=12)),
            ],
        ),
    ]
