# Generated by Django 4.2.1 on 2023-05-29 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIGT', '0005_alter_ticket_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Perfiles', '0002_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='perfil',
            name='user_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
