# Generated by Django 4.2.1 on 2023-06-19 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0003_delete_users_perfil_user_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name_plural': 'Perfiles'},
        ),
    ]
